Te 55 create decryptor module
weeve-modules/serial-data-decryptor pull request #3
Opened 2022-09-02 10:05 UTC by shriftz

- Added docker related files to publish module to docker bub
- Folder structure changes

2022-09-05 13:01 UTC, europaul approved these changes

2022-09-05 13:02 UTC, europaul commented
@unixdj could you review the go files here? you had many invaluable comments!

2022-09-08 13:07 UTC, unixdj requested changes, later dismissed

2022-09-08 13:07 UTC, unixdj commented on .editorconfig
> +indent_size = 4
```suggestion
indent_size = 8
```

2022-09-08 13:07 UTC, unixdj commented on docker/docker-entrypoint.sh
> +#!/bin/bash
anything bash-specific in this script?

2022-09-08 13:07 UTC, unixdj commented on docker/Dockerfile
> +# Oh yes, you need bash!
Yuck.  Bash.

2022-09-08 13:07 UTC, unixdj commented on docker/docker-entrypoint.sh
> +./app
Text files, especially shell scripts and source code, must end with a newline.

Guess how traditional `cpp` treated `#include` statements.

2022-09-08 13:07 UTC, unixdj commented on docker/docker-entrypoint.sh
> +elif [[ "$MODULE_TYPE" == "Output" ]]
normally spelled as `=`

2022-09-08 13:07 UTC, unixdj commented on example.env
> +AES_KEY=AAECAwQFBgcICQoLDA0ODw==
Environment is not the best place for secrets.

2022-09-08 13:07 UTC, unixdj commented on makefile
> +.phony: create_image
It's `.PHONY`, not `.phony`.  (Here and in other places.)

Does it actually work?  (You can check by creating a file `run_image`.)

2022-09-08 13:07 UTC, unixdj commented on makefile
> +MODULE=weevenetwork/serial-data-decryptor
These files are traditionally named `Makefile`, capitalised.  Not a technical requirement, just conservatism.

2022-09-08 13:07 UTC, unixdj commented on src/utility/env.go
>  func GetEnvAsserted(envVarName string) string {
Panicking functions in Go are traditionally called `Must*`, like `regexp.MustCompile` and such.  May or may nor make sense for fatalling functions.

2022-09-08 13:07 UTC, unixdj commented on src/utility/env.go
>  func GetEnvAsserted(envVarName string) string {
`envVarName`?  Either use `name` or something shorter, or go full microsoft hungarian notation and name it `sNameOfTheEnvironmentVariableThatWeAreTryingToRetrieveFromTheEnvironmentThatTherProcessIsRunningIn`.

From package "os":
```
func Getenv(key string) string
```

Also, there's this `Getenv` and there's the wonderfully named `godotenv` package (which doesn't parse `go.env`, of course, but it's ported from Roby so of course it's idiotic).  I didn't look into the interaction between the two, but I hope you know what you're doing.

2022-09-08 13:12 UTC, europaul commented on makefile
> +.phony: create_image
you are right, it doesn't. nice catch!

2022-09-08 13:13 UTC, europaul commented on src/utility/env.go
>  func GetEnvAsserted(envVarName string) string {
I don't really think that fits here

2022-09-08 13:14 UTC, europaul commented on example.env
> +AES_KEY=AAECAwQFBgcICQoLDA0ODw==
this is gonna change as soon as we introduce the secrets management

2022-09-12 08:21 UTC, merged